.\" Manpage for git-feature-branch.
.\" Contact sheldon.els@gmail.com to correct errors or typos.
.TH man 1 "21 July 2014" "0.2.1" "git-feature-branch man page"
.SH NAME
git-feature-branch \- Start a feature branch that will cleanly merge to other branches
.SH SYNOPSIS
git feature-branch <new_feature> [<upstream>...]
.SH DESCRIPTION
Creates a new branch <new_feature> from the common ancestor of all <upstream> branches. <new_feature> will cleanly merge to all <upstream> branches.
.SH OPTIONS
.PP
<new_feature>
.RS 4
The name of the new feature.
.RE
.PP
<upstream>...
.RS 4
The series of branches to be able to merge your new feature to in isolation from each other.
.RE
.SH SEE ALSO
git-merge-base(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Sheldon Els (sheldon.els@gmail.com)
