#!/usr/bin/env bash

set -e

usage() {
	cat <<- EOF

	usage: git feature-branch <new_feature> [<upstream>...]

	Creates a new branch <new_feature> from the common ancestor
	of all <upstream> branches. <new_feature> will cleanly
	merge to all <upstream> branches.

	If <upstream> is not specified it will default to origin/master.

	<upstream>... can be configured with: git config feature-branch.upstreams

	EOF
	exit 0
}

main() {
	# require first argument
	[ "$#" -gt 0 ] || usage

	local new_feature=$1
	shift
	local upstreams=$*

	if [[ -z $upstreams ]]; then
		local upstreams=$(git config feature-branch.upstreams)
	fi

	if [[ -z $upstreams ]]; then
		local upstreams="origin/master"
	fi

	local merge_base=$(git merge-base --octopus $upstreams)

	git checkout -b $new_feature $merge_base
}

main $*
